---
title: "Schedule for STT 4880 - Spring 2026"
author: "Dr. Hasthika Rupasinghe"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    toc: true
    css: "CSS/style.css"
---

***

**Week 1: (January 16 -- 19)**

* Go over syllabus.
* Chapter 6: Point Estimation ([6.1 - Descriptive Statistics](./LectureNotes/6_1.pdf))



***

**Week 2: (January 22 -- 26)** 

* Chapter 6: Point Estimation ([6.2 - Exploratory Data Analysis](./LectureNotes/6_2.pdf))
* In Class Quiz 01 (Thursday, last 20 minutes of class)
* [Homework 1: Due Thursday](Homework.html)


***

**Week 3: (January 29 -- February 2)**

* Chapter 6: Point Estimation ([6.3 - Order Statistics](./LectureNotes/6_3.pdf))
* In Class Quiz 02 (Thursday, last 20 minutes of class)
* [Homework 2: Due Thursday](Homework.html)

***

**Week 4: (February  5 -- 9)**

* Chapter 6: Point Estimation ([6.4 - Maximum Likelihood Estimation](./LectureNotes/6_4.pdf))
* [Maximum Likelihood Estimation --- Simulation](MLE.html)

* In Class Quiz 03 (Thursday, last 20 minutes of class)
* [Homework 3: Due Thursday](Homework.html)


***

**Week 5: (February 12 -- 16)**

**Reminder: Test 1 next week!**

* Chapter 7: Interval Estimation ([7.1 - Confidence Intervals for Means](./LectureNotes/7_1.pdf))
* [CI simulation - ](CI_SIM.html)
* In Class Quiz 04 (Thursday, last 20 minutes of class)
* [Homework 4: Due Thursday](Homework.html)

***

**Week 6: (February 19 -- 23)**

* Chapter 7: Interval Estimation ([7.2 - Confidence Intervals for the Difference
of Two Means](./LectureNotes/7_2.pdf))

* Test 01 (Thursday)


***

**Week 7: (February 26 -- March 1)**

* Exam 1 grades [distribution](GradesDensity.html)

* Chapter 7: Interval Estimation ([7.3 - Confidence Intervals for Proportions](./LectureNotes/7_3.pdf)) 
* In Class Quiz 05 (Thursday, last 20 minutes of class)
* [Homework 5: Due Tuesday](Homework.html)

***

**Week 8: (March 4 -- 8)**

* Chapter 7: Interval Estimation ([7.4 - Sample Size](./LectureNotes/7_4.pdf)) 

* [Homework 6: Due Thursday](Homework.html)

***

**Week 9: (March 11 --  15)**

* Spring Break- No classes


***

**Week 10: (March 18 -- 22)**

* Chapter 8: Tests of Statistical Hypotheses ([8.1 - Tests About One Mean](./LectureNotes/8_1.pdf)) 
* Chapter 8: Tests of Statistical Hypotheses ([8.2 - Tests of the Equality of Two Means](./LectureNotes/8_2.pdf))
* In Class Quiz 07 (Thursday, last 20 min of class)
* [Homework 7: Due Tuesday](Homework.html)

  

***

**Week 11: (March 25 -- 29)**


* Chapter 8: Tests of Statistical Hypotheses ([8.3 -Tests About Proportions](./LectureNotes/8_3.pdf))
* Chapter 8: Tests of Statistical Hypotheses ([8.4 -The Wilcoxon Tests](./LectureNotes/8_4.pdf))
* In Class Quiz 08 (Thursday, last 20 min of class)
* [Homework 8: Due Tuesday](Homework.html)


***

**Week 12: (April 1 -- April 5)**

* Chapter 8: Tests of Statistical Hypotheses ([8.4 -The Wilcoxon Tests](./LectureNotes/8_4.pdf))
* Reminder: Test 02 - Thursday the 13th (Covers section 7.1, 7.2, 7.3, 7.4, 8.1, 8.2)
* [Homework 9: Due Thursday](Homework.html)

***

**Week 13: (April 8 -- 12)**

* Chapter 8: Tests of Statistical Hypotheses ([8.4 -The Wilcoxon Tests](./LectureNotes/8_4.pdf))
* Test 2 Thursday


***

**Week 14: (April 15 -- 19)**

* Exam 2 grades [distribution]()

* Chapter 9: More Tests (9.1 - Chi-Square Goodness-of-Fit Tests)
* Chapter 9: More Tests (9.2 - Contingency Tables)


* In Class Quiz 09 (Thursday, last 20 min of class)
* [Homework 10: Due Thursday](Homework.html)


***

**Week 15: (April 22 -- 26)**

* Chapter 9: More Tests (9.3 - One-Factor Analysis of Variance)
* In Class Quiz 10 (Thursday, last 20 min of class)
* [Homework 11: Due Thursday](Homework.html)



***

**Week 16: (April 29 --  May 3)**

* May 1st is last day of classes
* Chapter 9: More Tests (9.3 - One-Factor Analysis of Variance)


***

* Final Exam is on May 9th from 8AM to 10.30AM

***

# [Home Page](https://hasthika.github.io/STT4880SP2022/index.html) - 



