---
title: "Schedule for STT 4880 - Spring 2021"
author: "Dr. Hasthika Rupasinghe"
date: 'Last Updated on: `r format(Sys.time(), "%b %d, %Y at %X")`'
output: 
  bookdown::html_document2: 
    highlight: textmate
    theme: yeti
    toc: true
    css: "CSS/style.css"
---

***

**Week 1: (January 18 -- 22)**

* Go over syllabus.
* Chapter 6: Point Estimation (6.1 - Descriptive Statistics)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/S76r370t-xKnXB260_P2ckgNdqn3aTDxh-ZTezDG3PNXsGMJE1b8ReEd_rLNqMGH.qI6WSKuCtqbxRuU_) 
  * [Thursday's Lecture](https://appstate.zoom.us/rec/share/iL0Ok-VxS8vnJlRmOqxRqEn0yr9g0JWmBOAIXyCSf8d-gDhsTrIDLVaeGAe5sl9A._IJwTyhTGnKVQNzc)

***

**Week 2: (January 25 -- 29)** 

* Chapter 6: Point Estimation (6.2 - Exploratory Data Analysis)
* In Class Quiz 01 (Thursday the 23rd, last 20 minutes of class)
* [Homework 1: Due Thursday the 28rd](Homework.html)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/QxaJHcCo0ipfyaF-WxKFDDWVoNaDXsMsHsaWhB8OtVMJ3X0fnIZ0QJ7iMAzHCqR4.wgLTYWRU601w6B6L)
  * [Thursday's Lecture](https://appstate.zoom.us/rec/share/5Ws-zJtcnkYx6BUDMCnaI8nzf4bWVmlmRPBNsHUaEI9ATPCqdUWmtw8NMtQ68tl6.0BvWksJj82ZFaZHt)

***

**Week 3: (February 01 -- 05)**

* Chapter 6: Point Estimation (6.3 - Order Statistics)
* In Class Quiz 02 (Thursday, last 20 minutes of class)
* [Homework 2: Due Thursday the 4th](Homework.html)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/hpz54vKnbO9R9xVTXyz7ln13hUIfIZlPytt6bjMlW7iJx8mH-K9pysQY-2_sVxgf.ME1u6uleMaarDAcQ)
  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/2jYj0mk8mGuMYyg0V2_003iZ_1_eV44yZRK_LT695q9VQ9MHtgAQuL4N6HU-24Pf.EvoDGuIBfYSnENEn)

***

**Week 4: (February 08 -- 12)**

* Chapter 6: Point Estimation (6.4 - Maximum Likelihood Estimation)
* In Class Quiz 03 (Thursday, last 20 minutes of class)
* [Homework 3: Due Thursday](Homework.html)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/ldU5qozpfK_0NsVPpkPXNAEMnd7KUCTlNqwkRPVaFiGnxmHidAc0TFFLXD9cbfY2.r8Nqa-EWnudI-fVV)
  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/n4uXXqGzixYz9q6ooJTSjrVoNHEk-RAhP74e0nJ7zzTjG11D-IsifcnRkEI9nIgj.KwLmEFs900ZPfd0u)  

***

**Week 5: (February 15 -- 19)**

**Reminder: Test 1 next week!**

* Chapter 7: Interval Estimation (7.1 - Confidence Intervals for Means)
* In Class Quiz 04 (Thursday the 13th , last 20 minutes of class)
* [Homework 4: Due Thursday](Homework.html)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/SQ7vpQAlhqqpDLbaYNq2MNFQM6BEcWeYoBNqiHFwrfE-8oSYL3agUIGMX4PoULbj.D5_hrQEATdOHGfuZ)
  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/7COzCCYP3oycM6vBWzuiOlp-AcA9A6W48tRhodp5ley9WNnkiUpgVbh1njqDi8Nh.NGqspanJg4vgsIJj)  

***

**Week 6: (February 22 -- 26)**

* Chapter 7: Interval Estimation (7.2 - Confidence Intervals for the Difference
of Two Means)

* Test 01 (Thursday)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/BF8XciHSRDqqWjGxd3pPB6aU022HAljqMfh67z1X0hOiTsHBfbKsIBakyQAdkP1T.cc24BoaJvq_UfFUX)
  * [Tuesday's Lecture]()  - Exam day, No recording
  

***

**Week 7: (March 01 -- 05)**

* Exam 1 grades [distribution](GradesDensity.html)

* Chapter 7: Interval Estimation (7.3 - Confidence Intervals for Proportions) 
* In Class Quiz 05 (Thursday the 27th , last 20 minutes of class)
* [Homework 5: Due Tuesday](Homework.html)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/wYybOQ-ngg7ATdSYtnEavhLZZDVkg0PIehz0icj99ePaus1bKsA9A7-PfhYnE4-m.o6Adkole2lA68bat)
  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/y6rbeNfNnjZKUBSgk7xR_NljlyjXybdbG6vx348CRx7c02t7A32ZnasZJE1-V6p6.ydfnv6UZZBz3PZ1i)  

***

**Week 8: (March 08 -- 12)**

* Chapter 7: Interval Estimation (7.4 - Sample Size) 

* [Homework 6: Due Thursday](Homework.html)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/yPBBZ1Jj-WO9HUcAgLZnDcEbHW4z1gPBlvxqI-TvhOmO5-yjNyMtum-S-qiLL8UD.I2IoBWhz1gjE6zDp)
  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/eLdvqpTxcr0XpM8hYFFKbDnykYymS7Y7Xf67ncx5WSGX0kainwCd1N8KhlVQ_InK.4U5EcYZNHUg67F9H)  

***

**Week 09: (March 15 -- 19)**

* Chapter 8: Tests of Statistical Hypotheses (8.1 - Tests About One Mean) 
* Chapter 8: Tests of Statistical Hypotheses (8.2 - Tests of the Equality of Two Means)
* In Class Quiz 07 (Thursday the 26th, last 20 min of class)
* [Homework 7: Due Tuesday](Homework.html)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/HVHU3xh6Z10YjhZBJD1XHW9ozDjMLQjDBe12-8FOMgCApyB7ZwY-h-raR8intDKW.xtTIaGcJMNR54AG8)
  * [Tuesday's Lecture]()  - day off
  

***

**Week 10: (March 22 -- 26)**


* Chapter 8: Tests of Statistical Hypotheses (8.3 -Tests About Proportions, 8.4 -The Wilcoxon Tests)
* In Class Quiz 08 (Thursday the 02nd, last 20 min of class)
* [Homework 8: Due Tuesday](Homework.html)


*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/CFfXOatpmCasPBqReVk0HLnK7fLnVkdDer-hCIPqn9IDfUDkwdpCMI-a3Ssfmus.aL885svGsZJ5LcLx)
  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/I2L4L_QI3m_akDDqDj766mTKJr8R9HUHpPc4LRSBk2ALbOVlm6lEdpPouepR5RFd._7Su1wxVuzHC4sLE)

<!--
* [Lecture Video for Section 8.3](https://appstate.zoom.us/rec/share/6_5LdrvJrD5OUo2V9l_7B_J5R4_8T6a813QZ-PRcmUzQ9t-lZ7hlhrnJeGD3HdDM)
* [Lecture Video for Section 8.4 part 1](https://appstate.zoom.us/rec/share/vuJeAYHK8GRJWJHO9lz9a4IbN4LjX6a8hCMZr6Jbyxozp6vTAIhJZarWwHtb1S4C)
-->

***

**Week 11: (March 29 -- April 02)**

* Chapter 8: Tests of Statistical Hypotheses (8.4 -The Wilcoxon Tests)
* Test 02 - Thursday the 08th (Covers section 7.1, 7.2, 7.3, 7.4, 8.1, 8.2)

*Lecture recordings*

  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/8YJUEut_GEvvDxhQul_2NvR5abXtT9uEKQRa5DjLHneA6Gse7dntH5kkjGSbMpDT.lmZPg5TUdcJk65f5)
  * [Tuesday's Lecture](https://appstate.zoom.us/rec/share/ASHSoICYU_RgNR-pzXENcC9TNzTrrsMmfGROrPrNDRfQ04f07I9gdTnvjoeIj7Ld.I-qGABs_XgWcv9r7)

<!--
* [Lecture Video for Section 8.4 part 2](https://appstate.zoom.us/rec/share/6_dbDYHI8EZOfZXXq2_jdJAuE5u6eaa8gyAf_vEKzEzaCrejg65aUdT3sVYzJU1L)
-->


***

**Week 12: (April 05 -- 09)**

* Chapter 9: More Tests (9.1 - Chi-Square Goodness-of-Fit Tests)
* Chapter 9: More Tests (9.2 - Contingency Tables)
* [Homework 9: Due Tuesday next week](Homework.html)
* Test 2 Thursday


<!--
* [Lecture Video for Section 9.1 part 1](https://appstate.zoom.us/rec/share/2NwqEp7c21hIHa-X-Hv8XKwxJtTaT6a8hnRN-fcKnR0hYPPM2NXIdwd5FCrXZrKU?startTime=1586870629000)
* [Lecture Video for Section 9.1 part 2](https://appstate.zoom.us/rec/share/wt1nBLLN20hOWJWT8H3xVr8ZPr-6T6a81SYe-6dfz6rhw08qzoraXJVsZ2e670E?startTime=1587043562000)
-->


***

**Week 13: (April 12 -- 16)**

* Chapter 9: More Tests (9.3 - One-Factor Analysis of Variance)
* In Class Quiz 09 (Thursday, last 20 min of class)
* In Class Quiz 10 (Thursday the 23rd, last 20 min of class)
* [Homework 10: Due Tuesday](Homework.html)

<!--
* [Lecture Video for Section 9.2](https://appstate.zoom.us/rec/share/vcJLcpb8rmpIcLOX7W_NQZEwFbnMeaa8hyIe-PBZzEr_Owcp7anSxvvg6PT_yPnX?startTime=1587475449000)
* [Lecture Video for Section 9.3](https://appstate.zoom.us/rec/share/1e11dejvznxLeaPX5UzCRfcEId7eeaa803AeqfQExR1MxdZ9cbd1-KbxFXfcMmYQ?startTime=1587648209000)
-->

***

**Week 14: (April 19 -- 23)**

* [Homework 11: Due Tuesday](Homework.html)
* Review for final

<!--
* [Lecture Video for Section 9.3 part 2](https://appstate.zoom.us/rec/share/1ZROLZr39UpOepXT2UffY44xJoXPX6a82yRI-adZzUYMy1cSlI_2wLt7Cxp51s-e?startTime=1588080305000)
-->

***

* Final Exam TBA

***

# [Home Page](https://hasthika.github.io/STT4880SP2021/index.html) - 



