---
title: "Exam 1 grades"
author: "Dr. Hasthika Rupasinghe"
date: '`r format(Sys.time(), "%b %d, %Y at %X")`'
output:
  bookdown::html_document2:
    highlight: textmate
    theme: yeti
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(ggplot2)
```

# STT 4880 Exam 2 grades Spring 2022.{-}

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(plotly)
library(ggplot2)
Class2 <- c(100,	88,	70,	63,	85,	60,		77,		82,	90,	70,	98,	98,	82,	95,	87,	55,		82,	100,	82,	70)


p2 <- ggplot(data = data.frame(Class2), aes(x = Class2)) + 
  geom_density(fill = "gold2") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") +
  geom_vline(xintercept=median(Class2), linetype="dotted") +
  annotate("text",x=median(Class2)+1,y=0.01,label="Exam Average = 82",hjust=0)

ggplotly(p2)


p3 <- ggplot(data = data.frame(Class2), aes(y = Class2)) + 
  geom_boxplot(fill = "pink") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") 

p3


library(dplyr)
library(knitr)

q <- quantile(Class2)

q <- as.matrix(q)
rownames(q) <- c("Min", "Q1", "Median", "Q3", "Max")
colnames(q) <- c("Value")
kable(q)


```

# STT 4880 Exam 1 grades Spring 2022.{-}

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(plotly)
library(ggplot2)
Class2 <- c(105,86,55,60,65,45,70,83,77,93,105,56,80,86,80,101,95,50,70,97,105,75,100,85)


p2 <- ggplot(data = data.frame(Class2), aes(x = Class2)) + 
  geom_density(fill = "orchid4") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") +
  geom_vline(xintercept=median(Class2), linetype="dotted") +
  annotate("text",x=median(Class2)+1,y=0.01,label="Exam Average = 80",hjust=0)

ggplotly(p2)


p3 <- ggplot(data = data.frame(Class2), aes(y = Class2)) + 
  geom_boxplot(fill = "pink") + 
  theme_bw() + 
  labs(x = "Exam 1 grades") 

p3


library(dplyr)
library(knitr)

q <- quantile(Class2)

q <- as.matrix(q)
rownames(q) <- c("Min", "Q1", "Median", "Q3", "Max")
colnames(q) <- c("Value")
kable(q)


```









